# Example configuration file for server.
# Save it to `config.yml` when edited

server:
  keepaliveperiodseconds: 0 # 0 = use Go default (15s); -1 = disable keepalive; set to interval in which keepalive packets will be sent. Only change this value if you know what you are doing.
  listenaddr: "" # address to bind on, leave empty to bind on all addresses. Prefix with "unix:" to create a unix socket. Example: "unix:/tmp/gotify.sock".
  port: 80 # port to HTTP server will listen on

  ssl:
    enabled: false # if https should be enabled
    redirecttohttps: true # redirect to https if site is accessed by http
    listenaddr: "" # address to bind on, leave empty to bind on all addresses. Prefix with "unix:" to create a unix socket. Example: "unix:/tmp/gotify.sock".
    port: 443 # https port
    certfile: # cert file (leave empty when using letsencrypt)
    certkey: # cert key (leave empty when using letsencrypt)
    letsencrypt:
      enabled: false # if certificate should be requested from letsencrypt
      accepttos: false # if you accept tos from letsencrypt
      cache: data/certs # directory of cache from letsencrypt
      directoryurl: # override the directory url of ACME server
                    # Let's Encrypt highly recommend testing against their staging environment before using their production environment.
                    # Staging server has high rate limits for testing and debugging, issued certificates are not valid
                    # example: https://acme-staging-v02.api.letsencrypt.org/directory
      hosts: # hosts for which letsencrypt should request certificates
#      - mydomain.tld
#      - myotherdomain.tld

  responseheaders: # response headers are added to every response (default: none)
#    X-Custom-Header: "custom value"
#
  trustedproxies: # IPs or IP ranges of trusted proxies. Used to obtain remote ip via the X-Forwarded-For header. (configure 127.0.0.1 to trust sockets)
#   - 127.0.0.1/32
#   - ::1

  cors: # Sets cors headers only when needed and provides support for multiple allowed origins. Overrides Access-Control-* Headers in response headers.
    alloworigins:
#      - ".+.example.com"
#      - "otherdomain.com"
    allowmethods:
#      - "GET"
#      - "POST"
    allowheaders:
#      - "Authorization"
#      - "content-type"
  stream:
    pingperiodseconds: 45 # interval in which websocket pings will be sent. Only change this value if you know what you are doing.
    allowedorigins: # allowed origins for websocket connections (same origin is always allowed)
#      - ".+.example.com"
#      - "otherdomain.com"

  ratelimit:
    enabled: true # enable rate limiting to protect against brute force attacks
    requestspersecond: 5 # maximum requests per second (default:5)
    burst: 10 # allow short bursts of requests (default: 10)

database: # for database see (configure database section)
  dialect: sqlite3
  connection: data/gotify.db

defaultuser: # on database creation, gotify creates an admin user
  name: admin # username of default user
  pass: admin # password of default user
passstrength: 10 # bcrypt password strength (higher = better but also slower)
uploadedimagesdir: data/images # directory for storing uploaded images
pluginsdir: data/plugins # directory where plugin resides
registration: false # enable registrations
